plugins {
    id("kmp-module")
}

kotlin {
    sourceSets {
        commonMain.dependencies {
            api(libs.multiplatform.settings)
            api(libs.kotlinx.datetime)
            implementation(libs.kotlinx.coroutines)
            implementation(libs.koin.core)
        }
        // `multiplatform-settings-no-arg` publishes no wasmJs variant (only `js`), so the web
        // target builds its Settings by hand — see platformSettings.wasmJs.kt.
        androidMain.dependencies { implementation(libs.multiplatform.settings.no.arg) }
        iosMain.dependencies { implementation(libs.multiplatform.settings.no.arg) }
        getByName("desktopMain").dependencies { implementation(libs.multiplatform.settings.no.arg) }
    }
}

/*
 * `AppConfig` is generated rather than written: `-Penv=<name>` selects `config/<name>.properties`,
 * whose keys are the whole schema, and `local.properties` then `APP_*` environment variables
 * override any of them. That is what keeps a token out of git — see "Configuration" in README.md.
 *
 * Everything the task reads goes through `providers`, so the configuration cache invalidates when
 * a config file, `local.properties` or an `APP_*` variable changes.
 */
val configPackage = "com.template.core.common.config"

val appEnvironment = providers.gradleProperty("env").orElse("dev")

val declaredConfig = appEnvironment
    .flatMap { providers.fileContents(layout.settingsDirectory.file("config/$it.properties")).asText }
    .orElse("")

val machineConfig = providers
    .fileContents(layout.settingsDirectory.file("local.properties"))
    .asText
    .orElse("")

val environmentConfig = providers.environmentVariablesPrefixedBy("APP_")

val generatedConfigDir = layout.buildDirectory.dir("generated/appConfig")

val generateAppConfig = tasks.register("generateAppConfig") {
    val environmentName = appEnvironment
    val declared = declaredConfig
    val machine = machineConfig
    val fromEnvironment = environmentConfig
    val outputDir = generatedConfigDir
    val packageName = configPackage
    val knownEnvironments = listOf("Dev", "Staging", "Prod")

    inputs.property("environment", environmentName)
    inputs.property("declared", declared)
    inputs.property("machine", machine)
    inputs.property("fromEnvironment", fromEnvironment)
    outputs.dir(outputDir)

    doLast {
        fun parse(text: String): Map<String, String> = text.lineSequence()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") && it.contains("=") }
            .associate { it.substringBefore("=").trim() to it.substringAfter("=").trim() }

        fun variableName(key: String): String =
            "APP_" + key.replace(Regex("([a-z0-9])([A-Z])"), "$1_$2").uppercase()

        val name = environmentName.get()
        val environmentConstant = name.replaceFirstChar { it.uppercaseChar() }
        require(environmentConstant in knownEnvironments) {
            "-Penv=$name has no constant in AppEnvironment.kt. Add `$environmentConstant` there, " +
                "and a config/$name.properties beside the others."
        }

        val keys = parse(declared.get())
        require(keys.isNotEmpty()) {
            "config/$name.properties is missing or declares nothing."
        }

        val overrides = parse(machine.get())
        val fromShell = fromEnvironment.get()

        val properties = keys.map { (key, fallback) ->
            val value = fromShell[variableName(key)] ?: overrides[key] ?: fallback
            require(value != "required") {
                "config/$name.properties marks `$key` as required. Put `$key=…` in " +
                    "local.properties, or set ${variableName(key)} in the environment."
            }
            val (type, literal) = when {
                value == "true" || value == "false" -> "Boolean" to value
                value.isNotEmpty() && value.all { it.isDigit() } -> "Int" to value
                else -> "String" to "\"${value.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}")}\""
            }
            "    val $key: $type = $literal"
        }

        val file = outputDir.get().asFile.resolve("AppConfig.kt")
        file.parentFile.mkdirs()
        file.writeText(
            buildList {
                add("// Generated by :core:common's generateAppConfig from config/$name.properties.")
                add("// Do not edit, and do not commit: this file holds whatever secrets the build was given.")
                add("package $packageName")
                add("")
                add("object AppConfig {")
                add("")
                add("    val environment: AppEnvironment = AppEnvironment.$environmentConstant")
                add("")
                addAll(properties)
                add("}")
                add("")
            }.joinToString("\n"),
        )
    }
}

kotlin.sourceSets.commonMain.get().kotlin.srcDir(generateAppConfig)
